### PR TITLE
fix: add 'window-management' to chromium browser fixes #1628 java-playwright

### LINKED ISSUE #1628: [Feature]: Add Window-management to chromium browser
### 🚀 Feature Request

we need to have another grant permissions to allow the windows-management permission popup

### Example

_No response_

### Motivation

permissions popup cannot add windows management permission for pop up windows blocking automation

### PR DESCRIPTION
**Pull request by imtheish97**
This fixes #1628 I have done the same fix for https://github.com/microsoft/playwright/issues/27198 of the js version but actually needed it for java

### CODE REVIEW

**Comment by mxschmitt** [comment]
This file is generated, with the next release it should be automatically getting updated.

**Comment by imtheish97** [comment]
> This file is generated, with the next release it should be automatically getting updated.

hi @mxschmitt what do you mean exactly? does the main playwright repo update playwright java?

**Comment by mxschmitt** [comment]
> > This file is generated, with the next release it should be automatically getting updated.
> 
> hi @mxschmitt what do you mean exactly? does the main playwright repo update playwright java?

Yes, before we release Playwright for Java, we port all the new features from microsoft/playwight to Java and the documentation etc. and interfaces get automatically generated / updated.

**Comment by imtheish97** [comment]
@mxschmitt is the implementation correct?

**Comment by imtheish97** [comment]
@mxschmitt nice thanks, do you know when playwright java will be updated? as this feature is now in playwright but there is no tag build for playwright java yet. Thanks for the help!

**Comment by mxschmitt** [comment]
We don't have an eta for that. Usually we release Java a week after Node.js. And Node.js we release every 4-6 weeks. For this feature, is no implementation in Java needed, since this is a server side only change.

I'll close it for now as per https://github.com/microsoft/playwright-java/pull/1629#issuecomment-2233007356.

**Comment by imtheish97** [comment]
> We don't have an eta for that. Usually we release Java a week after Node.js. And Node.js we release every 4-6 weeks. For this feature, is no implementation in Java needed, since this is a server side only change.
> 
> I'll close it for now as per [#1629 (comment)](https://github.com/microsoft/playwright-java/pull/1629#issuecomment-2233007356).

Thank you, I will wait for the next tag to hopefully use this

**Pull request closed without merging**
