### PR TITLE
fix(timeout): add additional validation checks for the timeout

### PR DESCRIPTION
**Pull request by sohbat17**
- Check if the timeout is positive number before setting the timeout configuration.
- Check if the timeout is positive number before setting the navigationTimeout configuration

### CODE REVIEW

**Comment by mxschmitt** [comment]
How can it ever be negative?

**Review by yury-s — COMMENTED** [review]
What user observable problem does this fix?

**Comment by srivatsa-cfp** [comment]
To avoid user settings negative values for timeout in PageImpl & BrowserContextImpl class.

**Comment by sohbat17** [comment]
To avoid user passing negative values for timeout in PageImpl and BrowserContextImpl class.

**Comment by sohbat17** [comment]
> How can it ever be negative?

    - In PageImpl & BrowserContextImpl class, there are 2 methods where timeout values are set. To avoid setting negative timeout values from these methods additional checks are added.

**Comment by yury-s** [comment]
> To avoid user passing negative values for timeout in PageImpl and BrowserContextImpl class.

I understand that, what I'm asking is whether setting negative value causes any issues in the behavior of the program?

**Comment by sohbat17** [comment]
> > To avoid user passing negative values for timeout in PageImpl and BrowserContextImpl class.
> 
> I understand that, what I'm asking is whether setting negative value causes any issues in the behavior of the program?

Setting negative will stop execution of statements and test execution flow. for example we usually keep a certain duration for the async user operations like waiting for response, dynamic page locator based on previous selection etc.

**Comment by yury-s** [comment]
Same will happen if one sets timeout to 0 or actually to anything close enough to 0.  Doesn't seem to make any difference from the user's stand point once the timeout is less than a few milliseconds - the behavior will be all the same.

**Pull request closed without merging**
